### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by joaomlneto** [emmdim/wibed_vis#1]
You forgot to close the HTML tag in test.html

**Comment by emmdim** [comment]
It was delibarate since it is done in all d3.js examples, like:
http://bl.ocks.org/mbostock/4062045

So I am following his recipe.

Thanxs for the posting though. What are you doing here? :-P

**Comment by joaomlneto** [comment]
### but... but... you will break the interwebs!! D:

"I am following his recipe" -- may be a recipe for disaster :smile: 

i'm just crawling github, poking people's repositories :stuck_out_tongue_winking_eye: 
let's have a beer september the latest! :P
